env:
  browser: true
  es2020: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
  - error
  - 4
  react/jsx-indent:
  - error
  - 4
  react/jsx-indent-props:
  - error
  - 4
  react/jsx-filename-extension:
  - 2
  - extensions:
    - ".ts"
    - ".tsx"
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-multi-spaces:
  - error